main: cn.mcres.karlatemp.pdevtool.PDevTool
name: PDevTool
version: 1.3
author: Karlatemp
website: https://github.com/Karlatemp
permissions:
  "pdevtool.command.psudo":
    default: op
  "pdevtool.command.pshow":
    default: op
  "pdevtool.command.pinfo":
    default: op
  "pdevtool.command.pclass":
    default: op
  "pdevtool.command.pevent":
    default: op
  "pdevtool.command.plog":
    default: op
commands:
  plog:
    description: "Real-time output check permission"
    permission: pedevtool.command.plog
    usage: "/plog"
    aliases:
      - prend
      - prt
  pexit:
    description: Exit SUDO mode
  psudo:
    description: "Using SUDO mode to run a command."
    usage: "/psudo -i | /psudo {command}"
    permission: pdevtool.command.psudo
    aliases:
      - ps
      - sud
  pshow:
    permission: pdevtool.command.pshow
    aliases:
      - psh
    description: Show command's permission in invoking
    usage: "/<command> {command}"
  pinfo:
    description: Show command's full info.
    aliases:
      - pi
    permission: pdevtool.command.pinfo
    usage: "/<command> {command}"
  pclass:
    description: Show class owner.
    aliases:
      - pcl
    permission: pdevtool.command.pclass
    usage: "/<command> {class}"
  pevent:
    description: Show event's event listeners
    permission: pdevtool.command.pevent
    usage: "/<command> {class}"